### ISSUE TITLE
Build Admin Page

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#117]
This issue builds the front-end for #113.

Build a dynamic admin page that allows displaying, modifying and saving the machine learning settings. Angular has a library called formly that can dynamically build form pages. A good example article on how to do this is here: https://scotch.io/tutorials/easy-angularjs-forms-with-angular-formly

Work with the ETL team to modify the JSON structure as needed to support form generation.

**Comment by dhuang89** [comment]
Added adminView.html and adminReject.html in /components/admin. adminView is for a successful login/authentication, while adminReject is for trying to access the admin page unauthorized. The majority of the formatting will be done in adminView. 

Also, CSS files are not loading correctly when accessing these views, this is most likely due to the res.redirect() methods in server.js. 

Another task will be to hide the login button and display logout & admin page buttons when a user is logged in.

**Comment by dhuang89** [comment]
CSS problem has been fixed, still need to work on toggling the buttons. Elasticsearch index has been connected, and we are currently working on formatting a table with the settings.

**Comment by davidmezzetti** [comment]
Make sure we don't hard code any form values on this page. The ETL side JSON has been designed to support dynamic form generation.

**Comment by davidmezzetti** [comment]
The admin page should have a whitelist of usernames that are allowed to access the page. This data would be stored with the settings.

**Comment by dhuang89** [comment]
As of now, the Admin page can read from Elasticsearch and populate the forms with the preset settings. The submit button does not work, and the issue is being closed due to time constraints.
